In [56]:
%pip install torch pandas summary


  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Obtaining dependency information for chardet from https://files.pythonhosted.org/packages/38/6f/f5fbc992a329ee4e0f288c1fe0e2ad9485ed064cac731ed2fe47dcc38cbf/chardet-5.2.0-py3-none-any.whl.metadata
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/31/58/e3b3dd6bb2ab7404f1f4992e2d0e6926ed40cef8ce1b3bbefd95877499e1/lxml-4.9.3-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/199.4 kB ? eta -:--:--
   ------ --------------------------------- 30.7/199.4 kB ? eta -:--:--
   ------------------ --------------------- 92.2/199.4 kB 1.3 MB/s eta 0:00:01
   ---------------------------------- ----- 174.1/199.4 kB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 199.4/199.4 kB 1.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0


[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [38]:
import torch
import torch.nn as nn

In [39]:
a=torch.IntTensor([1,1,2,3,4])
a

tensor([1, 1, 2, 3, 4], dtype=torch.int32)

In [40]:
# a=torch.tensor([1.01,1,2,3,4])
# a

In [41]:
a=torch.IntTensor([1,1,2,3,4])
b=torch.IntTensor([1,1,4,5,6])
a*b

tensor([ 1,  1,  8, 15, 24], dtype=torch.int32)

In [42]:
torch.dot(a,b)

tensor(49, dtype=torch.int32)

In [43]:
a=torch.rand((1,4))
b=torch.rand((4,1))
a*b

tensor([[0.0235, 0.0189, 0.0057, 0.0217],
        [0.4039, 0.3247, 0.0980, 0.3741],
        [0.1700, 0.1366, 0.0412, 0.1574],
        [0.3251, 0.2613, 0.0789, 0.3011]])

In [44]:
a@b

tensor([[0.6905]])

Размерность

In [45]:
a.shape

torch.Size([1, 4])

In [46]:
a.size()

torch.Size([1, 4])

Добавление размерности

In [47]:
a[None, :].shape

torch.Size([1, 1, 4])

In [48]:
a.view(-1,1).shape

torch.Size([4, 1])

In [49]:
a.T

tensor([[0.4759],
        [0.3825],
        [0.1154],
        [0.4407]])

In [50]:
from torch.utils.data import Dataset, DataLoader

In [51]:
import pandas as pd

In [52]:
df = pd.read_csv('iris.csv')
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [53]:
class IrisDataset(Dataset):
    def __init__(self, dataframe:pd.DataFrame):
        self.df=dataframe
    def __len__(self):
        return self.df.shape[0]
    def __gettitem__(self,ind):
        raw=self.df.loc[ind].to_numpy()
        target=raw[-1]
        target=torch.Tensor

In [54]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.linear1=nn.Linear(4,32)
        self.f_act=nn.ReLu()
        self.linear2=nn.Linear(32,3)
        self.softmax=nn.Softmax(dim=1)
    def forward(self,X):
        res=self.linear1(X)
        res=self.f_act(res)
        res=self.linear2(res)
        res=self.softmax(res)
        return res

In [57]:
from torchsummary import summary
summary(Net())

AttributeError: module 'torch.nn' has no attribute 'ReLu'